# Deploy this on each VALIDATOR server
# Run: docker compose up -d

version: "3.8"

services:
  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - promtail-positions:/tmp
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped
    network_mode: host

volumes:
  promtail-positions:
